### ISSUE TITLE
How did R server pickup dependencies like Tensor Flow

### ISSUE THREAD

**Issue by rahulravindran0108** [rajshah4/tensorflow_shiny#1]
Note:It is not an issue but a question that I have

How did python command pickup dependencies like Tensor flow when you published the app on shiny server ? I am working on running Theano and not tensor flow.

**Comment by rajshah4** [comment]
I first installed everything and had it all working with just python.  Then i was able to use the rPython command to call tensorflow.  The first couple lines with rPython are importing the necessary modules, e.g. tensorflow, pandas . .  .  
If you are trying to do an app with Theano, my first suggestion is to get everything in theano working.  Then install R, add the rPython library, and see if rPython can call everything in your python script.  Once that is working, you can move to wrapping it in Shiny.  
Does this make sense?  
(And I found your notebooks helpful for learning tensorflow)

**Comment by rahulravindran0108** [comment]
Okay, thanks a lot :).

When you deployed your shiny app, did those package import work ? cause my sklearn packages could not be found.
